# Generated by Django 5.1.3 on 2025-01-28 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0003_product_model_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem_model',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem_model',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orderitem_model',
            name='product_name',
        ),
        migrations.AddField(
            model_name='orderitem_model',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_model'),
        ),
    ]
