# Generated by Django 5.1.3 on 2025-01-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='image',
            field=models.ImageField(upload_to='products/image/'),
        ),
    ]
