# Generated by Django 5.1.3 on 2025-02-20 08:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_model',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='category/image'),
        ),
        migrations.AlterField(
            model_name='product_model',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='products/image'),
        ),
    ]
